### ISSUE TITLE
Intake Subsystem

### ISSUE THREAD

**Issue by nmot919** [chopshop-166/frc-2022#3]
**Intake**

**What is the primary purpose?**
To pick up cargo off the ground.
**What operations does it need to do?**
- Deploy/retract roller.
- Pick up cargo from the ground.
- Turn on/off the roller.

**What does the subsystem need to know?**
- What position the intake mechanism is in.
- Whether the roller is spinning or not.
- The color of the ball the intake mechanism picks up.

**What actuators are on the subsystem?**
- 2 motors; one for roller, one for deployment.

**What sensors are on the subsystem?**
- Color sensor.
- (Maybe) limiting switch for deployment.

**How can the subsystem fail?**
The subsystem will fail it if cannot pick up cargo, this can happen either from the intake mechanism being jammed, the roller failing to spin, or the intake mechanism failing to be deployed.
Limit switch failure driving the intake into the ground and/or the robot.

**How can we mitigate failure?**
Make sure the intake mechanism can be deployed reliably and also roller spinning successfully(in the right direction). 
Current based limiting of deployment.
Time based limiting of deployment.

**What can be automated?**
Intake deployment, color sensing.

**Notes**
- Having color sensors on the intake mechanism itself may be an issue because if you have two cargo on the correct color and one the wrong color it will shoot out both. Having a ball shunting system in the transport itself will solve this issue.

**Comment by JoeJanickiChSh** [comment]
- [x] Deploy/retract roller
- [x] Turn roller on/off
- [x] Limit switches
- [x] Color sensing
- [x] Tune current limits
- [x] Testing

**Comment by bot190** [comment]
Intake has been working well! Closing this.
