### ISSUE TITLE
Week 5 Autonomous

### ISSUE THREAD

**Issue by msoucy** [chopshop-166/frc-2022#32]
Week 5 goal: Score and drive off tarmac

This will need, at minimum, "drive distance" and "turn angle" commands, as well as automatic shooting.

Depends on #31

**Comment by jeffaburke** [comment]
- [ ] Tune PID Controllers
- [ ] Create Trajectory Following Code
- [x] Create A Two Ball Path
- [x] Create Another Two Ball Path
- [x] Create A Three Ball Path
- Create Another Three Ball Path (Not viable really)

**Comment by msoucy** [comment]
Done as of Week 5
