### ISSUE TITLE
Shooter Subsystem

### ISSUE THREAD

**Issue by lilbites21** [chopshop-166/frc-2022#4]
**Subsystem Name**
Shooter
**What is the primary purpose?**
Aim laterally, aim angle, shoot
**What operations does it need to do?**
- needs to be able to rotate the base
- change the shoot angle
- change the velocity
- fire when wanted

**What does the subsystem need to know?**
- what its current angle is(so it doesn't over extend)
- its current velocity
- user input to shoot and to aim

**What actuators are on the subsystem?**
- a motor that changes its longitude angle  
- a motor to change its change is lateral angle
- a motor for the system that puts the ball into the shooter

**What sensors are on the subsystem?**
- vision
- encoder for seeing how fast you are throwing it

**How can the subsystem fail?**
if it cant shoot accurately
cant get a accurate reading on the sensors
**How can we mitigate failure?**
make sure that the sensors are calibrated and correct;
**What can be automated?**
aiming well
change the velocity to make it into the gold with a given angle

**Comment by bot190** [comment]
Just note that the current design does not have any control over the shooters rotational angle or launch angle. We will have to rotate the robot's drive base to adjust our aim towards the target.

Concerning potential failures:
1. Unable to get target angle
2. Unable to get target distance

How do we provide manual overrides for these failure cases?

**Comment by JoeJanickiChSh** [comment]
- [x] Change the velocity
- [x] Fire when wanted
