### ISSUE TITLE
Ball Transport Subsystem

### ISSUE THREAD

**Issue by nmot919** [chopshop-166/frc-2022#6]
**Ball Transport**

**What is the primary purpose?**
Transport cargo from the intake mechanism to the shooter.
**What operations does it need to do?**
- Detect cargo entering through the intake mechanism.
- Detect color of cargo entering through intake mechanism.
- Shunt cargo from transport if it is the wrong color.
- Transport cargo from intake to shooter.

**What does the subsystem need to know?**
- Color of the cargo entering the transport subsystem.

**What actuators are on the subsystem?**
- 1 motor per conveyor system.
- 1 motor for shunting system.

**What sensors are on the subsystem?**
- Color sensor.
- Cargo detecting sensor(maybe two).

**How can the subsystem fail?**
Not transporting the cargo from intake to shooter, not getting rid of the correct colored ball.
Any of the sensors failing remove automation.
Motor failure

**How can we mitigate failure?**
Make sure cargo can get from point A to B before everything else.
Have override for getting rid of cargo.
Make sure the ball can always get to the shooter whether or not the sensor is working.

**What can be automated?**
Ball shunting can be automated, the transport mechanism itself should be automated.

**Comment by msoucy** [comment]
Why might it not transport from intake to shooter?
How does the shunting system work?
Can the shunt system run at the same time as the conveyors?
Is there more than one conveyor?

**Comment by bot190** [comment]
![image](https://user-images.githubusercontent.com/6110918/151275762-11ac21b2-2b22-4369-84a1-474857978f63.png)

**Comment by JoeJanickiChSh** [comment]
- [x] Detect cargo entering through the intake mechanism.
- [ ] Detect color of cargo entering through intake mechanism.
- [ ] Shunt cargo from transport if it is the wrong color.
- [x] Transport cargo from intake to shooter.

**Comment by msoucy** [comment]
This is as feature-complete as we want it to be.
